on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  preview:
    runs-on: ubuntu-latest
    permissions: write-all
    steps:
      - name: Check Out Repo
        uses: actions/checkout@v3

      - name: Set up build timestamp
        run: echo "timestamp=$(date +%Y%m%d)" >> $GITHUB_ENV
      
      - name: Login to Quay.io
        uses: docker/login-action@v2
        with:
          registry: quay.io
          username: ${{ secrets.QUAY_USERNAME }}
          password: ${{ secrets.QUAY_PASSWORD }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
        with:
          version: latest

      - name: Build and push docker image
        uses: docker/build-push-action@v3
        with:
          context: ./
          file: ./Dockerfile
          platforms: linux/amd64
          push: true
          tags: quay.io/searxng/searxng-test-pr:pr-${{ github.event.number }}, quay.io/searxng/searxng-test-pr:pr-${{ github.event.number }}-${{ env.timestamp }}
          labels: quay.expires-after=20w

      - name: Helm Installation
        uses: azure/setup-helm@v3

      - name: Install kubectl
        uses: azure/setup-kubectl@v3

      - name: deploy to test k8s cluster
        run: |
          mkdir -p ~/.kube
          echo "$KUBECONFIG_TEXT" > ~/.kube/config
          chmod 600 ~/.kube/config
          helm repo add searxng https://charts.searxng.org
          helm repo update
          helm install --wait --create-namespace --namespace pr-${{ github.event.number }} searxng searxng/searxng \
            --set image.repository=quay.io/searxng/searxng-test-pr
            --set image.tag=pr-${{ github.event.number }}
            --set searxng.config.server.secret_key=secret
            --set env.BASE_URL="https://${{ github.event.number }}.testpr.searxng.net"
            --set env.INSTANCE_NAME="pr-${{ github.event.number }}"
            --set ingress.main.enabled=true
            --set "ingress.hosts[0].host=${{ github.event.number }}.testpr.searxng.net,ingress.hosts[0].paths[0].path=/,ingress.hosts[0].paths[0].pathType=Prefix"
            --set "ingress.tls[0].hosts[0]=${{ github.event.number }}.testpr.searxng.net,ingress.tls[0].secretName=pr-${{ github.event.number }}"
        env:
          KUBECONFIG_TEXT: ${{secrets.KUBECONFIG_TEST_CLUSTER}}