on:
  pull_request:
    types:
      - closed

jobs:
  closed:
    runs-on: ubuntu-latest
    steps:
      - name: Helm Installation
        uses: azure/setup-helm@v3

      - name: Install kubectl
        uses: azure/setup-kubectl@v3

      - name: deploy to test k8s cluster
        run: |
          mkdir -p ~/.kube
          echo "$KUBECONFIG" > ~/.kube/config
          chmod 600 ~/.kube/config
          helm uninstall -n pr-${{ github.event.number }} searxng
          kubectl delete namespace pr-${{ github.event.number }}